[workspace]
members = [
    "opentelemetry",
    "opentelemetry-api",
    "opentelemetry-aws",
    "opentelemetry-aws/examples",
    "opentelemetry-contrib",
    "opentelemetry-datadog",
    "opentelemetry-dynatrace",
    "opentelemetry-dynatrace/examples/dynatrace",
    "opentelemetry-http",
    "opentelemetry-http/examples",
    "opentelemetry-jaeger",
    "opentelemetry-jaeger/examples/actix-udp",
    "opentelemetry-jaeger/examples/tonic",
    "opentelemetry-jaeger/examples/remote-sampler",
    "opentelemetry-appender-log",
    "opentelemetry-otlp",
    "opentelemetry-prometheus",
    "opentelemetry-proto",
    "opentelemetry-sdk",
    "opentelemetry-semantic-conventions",
    "opentelemetry-stackdriver",
    "opentelemetry-stdout",
    "opentelemetry-zipkin",
    "opentelemetry-zpages",
    "opentelemetry-otlp/examples/basic-otlp",
    "opentelemetry-otlp/examples/basic-otlp-http",
    "opentelemetry-otlp/examples/external-otlp-grpcio-async-std",
    "opentelemetry-otlp/examples/external-otlp-tonic-tokio",
    "examples/actix-http",
    "examples/actix-http-tracing",
    "examples/actix-hyper",
    "examples/async",
    "examples/metrics-basic",
    "examples/logs-basic",
    "examples/traceresponse",
    "examples/tracing-grpc",
    "examples/multiple-span-processors",
    "stress",
]
