exclude=[
    "actix-http",
    "actix-http-tracing",
    "actix-udp",
    "actix-udp-example",
    "tracing-grpc",
    "http"
]

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "OpenSSL"
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    "RUSTSEC-2021-0127", # serde_cbor is unmaintained. However, we only depend on it indirectly through criterion, which is a dev dependency.
    "RUSTSEC-2021-0139", # ansi_term is unmaintained. It's used in 1) criterion, which is a dev dependency. 2) grpcio, but only in build.
    "RUSTSEC-2020-0036", # failure is deprecated. It's used in protoc-grpcio, which is a build dependency.
    "RUSTSEC-2019-0036", # Possible UB in failures, which is used in protoc-grpcio. We only use it in dev. See https://github.com/mtp401/protoc-grpcio/issues/40
]