version: "3"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "5775:5775/tcp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14628:14628"
      - "14250:14250"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
