name: integration tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.label.name == 'integration_tests' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run integration tests using docker compose
        run: ./scripts/integration_tests.sh
